/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : ADC0.c
**     Project     : S12Z_CAN_DBW
**     Processor   : MC9S12ZVCA192MLF
**     Component   : ADC
**     Version     : Component 01.699, Driver 01.00, CPU db: 3.00.000
**     Compiler    : CodeWarrior HCS12Z C Compiler
**     Date/Time   : 2022-01-04, 11:40, # CodeGen: 4
**     Abstract    :
**         This device "ADC" implements an A/D converter,
**         its control methods and interrupt/event handling procedure.
**     Settings    :
**          Component name                                 : ADC0
**          A/D converter                                  : ADC0
**          Sharing                                        : Disabled
**          Interrupt service/event                        : Enabled
**            A/D interrupt                                : Vadc0conv_compl
**            A/D interrupt priority                       : medium priority
**            Error interrupt                              : Vadc0err
**            Error interrupt priority                     : medium priority
**            Abort interrupt                              : Vadc0conv_seq_abrt
**            Abort interrupt priority                     : medium priority
**          A/D channels                                   : 6
**            Channel0                                     : 
**              A/D channel (pin)                          : PAD0_KWAD0_AN0_ACMP0_0
**              A/D channel (pin) signal                   : 
**            Channel1                                     : 
**              A/D channel (pin)                          : PAD1_KWAD1_AN1_ACMP0_1_ETRIG0
**              A/D channel (pin) signal                   : 
**            Channel2                                     : 
**              A/D channel (pin)                          : PAD2_KWAD2_AN2_ACMPO0
**              A/D channel (pin) signal                   : 
**            Channel3                                     : 
**              A/D channel (pin)                          : PAD3_KWAD3_AN3_VRH_0_ACMP1_0
**              A/D channel (pin) signal                   : 
**            Channel4                                     : 
**              A/D channel (pin)                          : PAD4_KWAD4_AN4_ACMP1_1
**              A/D channel (pin) signal                   : 
**            Channel5                                     : 
**              A/D channel (pin)                          : PAD5_KWAD5_AN5_ACMPO1
**              A/D channel (pin) signal                   : 
**          Queue                                          : Enabled
**            Mode                                         : Sequential
**            A/D samples                                  : 6
**              Sample0                                    : Enabled
**                Channel                                  : 0
**                Sample time                              : 10 ADC clock cycles
**                High volt. ref. source                   : VRH_1
**                Low volt. ref. source                    : VRL_1
**              Sample1                                    : Enabled
**                Channel                                  : 1
**                Sample time                              : 10 ADC clock cycles
**                High volt. ref. source                   : VRH_1
**                Low volt. ref. source                    : VRL_1
**              Sample2                                    : Enabled
**                Channel                                  : 2
**                Sample time                              : 10 ADC clock cycles
**                High volt. ref. source                   : VRH_1
**                Low volt. ref. source                    : VRL_1
**              Sample3                                    : Enabled
**                Channel                                  : 3
**                Sample time                              : 10 ADC clock cycles
**                High volt. ref. source                   : VRH_1
**                Low volt. ref. source                    : VRL_1
**              Sample4                                    : Enabled
**                Channel                                  : 4
**                Sample time                              : 10 ADC clock cycles
**                High volt. ref. source                   : VRH_1
**                Low volt. ref. source                    : VRL_1
**              Sample5                                    : Enabled
**                Channel                                  : 5
**                Sample time                              : 10 ADC clock cycles
**                High volt. ref. source                   : VRH_1
**                Low volt. ref. source                    : VRL_1
**          A/D resolution                                 : 12 bits
**          Conversion time                                : 17.4375 µs
**          Result mode                                    : Left justified/unsigned
**          External trigger                               : Disabled
**          Internal trigger                               : Disabled
**          Number of conversions                          : 2
**          Initialization                                 : 
**            Enabled in init. code                        : yes
**            Events enabled in init.                      : yes
**          CPU clock/speed selection                      : 
**            High speed mode                              : This component enabled
**            Low speed mode                               : This component disabled
**            Slow speed mode                              : This component disabled
**          High input limit                               : 1
**          Low input limit                                : 0
**          Get value directly                             : yes
**          Wait for result                                : yes
**     Contents    :
**         Start          - byte ADC0_Start(void);
**         Measure        - byte ADC0_Measure(bool WaitForResult);
**         GetValue16     - byte ADC0_GetValue16(word *Values);
**         GetChanValue16 - byte ADC0_GetChanValue16(byte Channel, word *Value);
**
**     Copyright : 1997 - 2014 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file ADC0.c
** @version 01.00
** @brief
**         This device "ADC" implements an A/D converter,
**         its control methods and interrupt/event handling procedure.
*/         
/*!
**  @addtogroup ADC0_module ADC0 module documentation
**  @{
*/         

/* MODULE ADC0. */

#include "Events.h"
#include "ADC0.h"
#define IDLE                            0x00U                    /* IDLE state                          */
#define SINGLE                          0x01U                    /* SINGLE state                        */
#define MEASURE                         0x02U                    /* MESURE state                        */
#define CONTINUOUS                      0x04U                    /* CONTINUOUS state                    */

#define CMD_EOL                         0xC0000000U              /* Command End of list used as the last command in CSL */
#define CMD_EOL_CONTINUOUS              0x80000000U              /* Command End of list with continuous measurement of the whole list used as the last command in CSL */
#define CLEAR_CMD_EOL                   0x3FFFFFFFU              /* Constant for clearing the EOL command - for channel methods */

#pragma DATA_SEG DEFAULT               /* Select data segment "DEFAULT" */

static volatile dword CSL[6] __attribute__ ((aligned (4))) = {   /* Channel/Sample settings */
0x00D03000U,0x00D13000U,0x00D23000U,0x00D33000U,0x00D43000U,0xC0D53000U};
static volatile word RVL[12] __attribute__ ((aligned (4)));      /* HW DMA result buffer */
static volatile bool OutFlg;                                     /* Measurement finish flag */
static volatile word ModeFlg;                                    /* Current state of device */
static volatile byte SumCnt;                                     /* Number of conversions */
static volatile dword ADC0_SumV[6];                              /* Temporary sum of measured values updated by conversion */
static volatile dword ADC0_OutV[6];                              /* Stable sum of measured values used in GetVal methods */

#define CMD_LAST_SAMPLE_PLUS_EOL 0xC0D53000U                     /* Last sample with command End of list */
#define CMD_LAST_SAMPLE_PLUS_EOL_CONTINUOUS 0x80D53000U          /* Last sample with command End of list */
/*
** ===================================================================
**     Method      :  ADC0_Start (component ADC)
*/
/*!
**     @brief
**         This method starts continuous conversion on all channels
**         that are set in the component inspector. When each
**         measurement on all channels has finished the [OnEnd ] event
**         may be invoked. This method is not available if the
**         [interrupt service] is disabled and the device doesn't
**         support the continuous mode. Note: If time of measurement is
**         too short and the instruction clock is too slow then the
**         conversion complete interrupt and its handler may cause a
**         system overflow.
**     @return
**                         - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
**                           ERR_DISABLED - Device is disabled
**                           ERR_BUSY - A conversion is already running
*/
/* ===================================================================*/
byte ADC0_Start(void)
{
  if (ModeFlg != IDLE) {               /* Is the device in running mode? */
    return ERR_BUSY;                   /* If yes then error */
  }
  ModeFlg = CONTINUOUS;                /* Set state of device to the CONTINUOUS mode */
  OutFlg = FALSE;                      /* Reset measured value validity */
  SumCnt = 0x00U;                      /* Clear the number of conversions */
  /* Note: Next 6 lines are speed optimized */
  ADC0_SumV[0] = 0U;                   /* Set variable for storing measured values to 0 */
  ADC0_SumV[1] = 0U;                   /* Set variable for storing measured values to 0 */
  ADC0_SumV[2] = 0U;                   /* Set variable for storing measured values to 0 */
  ADC0_SumV[3] = 0U;                   /* Set variable for storing measured values to 0 */
  ADC0_SumV[4] = 0U;                   /* Set variable for storing measured values to 0 */
  ADC0_SumV[5] = 0U;                   /* Set variable for storing measured values to 0 */
  while((ADC0STS & ADC0STS_READY_MASK) == 0x00U) {} /* Wait until the periphery is in idle state */
  /* ADC0FLWCTL: SEQA=0,TRIG=0,RSTA=1,LDOK=0,??=0,??=0,??=0,??=0 */
  setReg8(ADC0FLWCTL, 0x20U);          /* RSTA for initial command load */ 
  while(ADC0FLWCTL != 0x00U) {}        /* Wait until the restart event is not finished */
  /* ADC0FLWCTL: SEQA=0,TRIG=1,RSTA=0,LDOK=0,??=0,??=0,??=0,??=0 */
  setReg8(ADC0FLWCTL, 0x40U);          /* TRIG for start of the measurement */ 
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  ADC0_Measure (component ADC)
*/
/*!
**     @brief
**         This method performs one measurement on all channels that
**         are set in the component inspector. (Note: If the [number of
**         conversions] is more than one the conversion of A/D channels
**         is performed specified number of times.)
**     @param
**         WaitForResult   - Wait for a result of a
**                           conversion. If [interrupt service] is
**                           disabled, A/D peripheral doesn't support
**                           measuring all channels at once or Autoscan
**                           mode property isn't enabled and at the same
**                           time the [number of channels] is greater
**                           than 1, then the WaitForResult parameter is
**                           ignored and the method waits for each
**                           result every time. If the [interrupt
**                           service] is disabled and a [number of
**                           conversions] is greater than 1, the
**                           parameter is ignored and the method also
**                           waits for each result every time.
**     @return
**                         - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
**                           ERR_DISABLED - Device is disabled
**                           ERR_BUSY - A conversion is already running
*/
/* ===================================================================*/
byte ADC0_Measure(bool WaitForResult)
{
  if (ModeFlg != IDLE) {               /* Is the device in running mode? */
    return ERR_BUSY;                   /* If yes then error */
  }
  ModeFlg = MEASURE;                   /* Set state of device to the MEASURE mode */
  OutFlg = FALSE;                      /* Reset measured value validity */
  SumCnt = 0x00U;                      /* Clear the number of conversions */
  /* Note: Next 6 lines are speed optimized */
  ADC0_SumV[0] = 0U;                   /* Set variable for storing measured values to 0 */
  ADC0_SumV[1] = 0U;                   /* Set variable for storing measured values to 0 */
  ADC0_SumV[2] = 0U;                   /* Set variable for storing measured values to 0 */
  ADC0_SumV[3] = 0U;                   /* Set variable for storing measured values to 0 */
  ADC0_SumV[4] = 0U;                   /* Set variable for storing measured values to 0 */
  ADC0_SumV[5] = 0U;                   /* Set variable for storing measured values to 0 */
  while((ADC0STS & ADC0STS_READY_MASK) == 0x00U) {} /* Wait until the periphery is in idle state */
  /* ADC0FLWCTL: SEQA=0,TRIG=0,RSTA=1,LDOK=0,??=0,??=0,??=0,??=0 */
  setReg8(ADC0FLWCTL, 0x20U);          /* RSTA for initial command load */ 
  while(ADC0FLWCTL != 0x00U) {}        /* Wait until the restart event is not finished */
  /* ADC0FLWCTL: SEQA=0,TRIG=1,RSTA=0,LDOK=0,??=0,??=0,??=0,??=0 */
  setReg8(ADC0FLWCTL, 0x40U);          /* TRIG for start of the measurement */ 
  if (WaitForResult) {                 /* Is WaitForResult TRUE? */
    while (ModeFlg != IDLE) {}         /* If yes then wait for end of measurement */
  }
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  ADC0_GetValue16 (component ADC)
*/
/*!
**     @brief
**         This method returns the last measured values of all channels.
**         Compared with [GetValue] method this method returns more
**         accurate result if the [number of conversions] is greater
**         than 1 and [AD resolution] is less than 16 bits. In addition,
**         the user code dependency on [AD resolution] is eliminated.
**     @param
**         Values          - Pointer to the array that contains
**                           the measured data.
**     @return
**                         - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
**                           ERR_NOTAVAIL - Requested value not
**                           available
**                           ERR_OVERRUN - External trigger overrun flag
**                           was detected after the last value(s) was
**                           obtained (for example by GetValue). This
**                           error may not be supported on some CPUs
**                           (see generated code).
*/
/* ===================================================================*/
byte ADC0_GetValue16(word *Values)
{
  if (!OutFlg) {                       /* Is measured value(s) available? */
    return ERR_NOTAVAIL;               /* If no then error */
  }
    *Values++ = (word)((word)(ADC0_OutV[0]/0x02U)); /* Store averaged conversion data to user buffer */
    *Values++ = (word)((word)(ADC0_OutV[1]/0x02U)); /* Store averaged conversion data to user buffer */
    *Values++ = (word)((word)(ADC0_OutV[2]/0x02U)); /* Store averaged conversion data to user buffer */
    *Values++ = (word)((word)(ADC0_OutV[3]/0x02U)); /* Store averaged conversion data to user buffer */
    *Values++ = (word)((word)(ADC0_OutV[4]/0x02U)); /* Store averaged conversion data to user buffer */
    *Values++ = (word)((word)(ADC0_OutV[5]/0x02U)); /* Store averaged conversion data to user buffer */
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  ADC0_GetChanValue16 (component ADC)
*/
/*!
**     @brief
**         This method returns the last measured value of the required
**         channel. Compared with [GetChanValue] method this method
**         returns more accurate result if the [number of conversions]
**         is greater than 1 and [AD resolution] is less than 16 bits.
**         In addition, the user code dependency on [AD resolution] is
**         eliminated.
**     @param
**         Channel         - Channel number. If only one
**                           channel in the component is set then this
**                           parameter is ignored.
**     @param
**         Value           - Pointer to the measured value.
**     @return
**                         - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
**                           ERR_NOTAVAIL - Requested value not
**                           available
**                           ERR_RANGE - Parameter "Channel" out of
**                           range
**                           ERR_OVERRUN - External trigger overrun flag
**                           was detected after the last value(s) was
**                           obtained (for example by GetValue). This
**                           error may not be supported on some CPUs
**                           (see generated code).
*/
/* ===================================================================*/
byte ADC0_GetChanValue16(byte Channel, word *Value)
{
  if (Channel >= 6U) {                 /* Is the sample number out of range? */
    return ERR_RANGE;                  /* If yes then error */
  }
  if (!OutFlg) {                       /* Is measured value(s) available? */
    return ERR_NOTAVAIL;               /* If no then error */
  }
    *Value = (word)((word)(ADC0_OutV[Channel]/0x02U)); /* Store averaged conversion data to user buffer */
  return ERR_OK;                       /* OK */
}


/*
** ===================================================================
**     Method      :  ADC0_Interrupt (component ADC)
**
**     Description :
**         The method services the interrupt of the selected peripheral(s)
**         and eventually invokes event(s) of the component.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
#pragma CODE_SEG __NEAR_SEG NON_BANKED
ISR(ADC0_Interrupt)
{
  word temp0;                          /* MISRA side effect eliminator */
  volatile word *ResPointer;           /* Pointer to result buffer for reading of the current results */

  /* ADC0CONIF: CON_IF15=0,CON_IF14=0,CON_IF13=0,CON_IF12=0,CON_IF11=0,CON_IF10=0,CON_IF9=0,CON_IF8=0,CON_IF7=0,CON_IF6=0,CON_IF5=0,CON_IF4=0,CON_IF3=0,CON_IF2=0,CON_IF1=0,EOL_IF=1 */
  setReg16(ADC0CONIF, 0x01U);          /* Clear scan cycle complete flag */ 
  if (ModeFlg == IDLE) {               /* Is the driver in IDLE mode? */
    return;
  }
  ResPointer = ((ADC0EOLRI & ADC0EOLRI_RVL_EOL_MASK)?(RVL+ADC0CROFF1):RVL); /* Select the result buffer with current results */
  temp0 = *ResPointer++;               /* Save measured value to temporary variable */
  ADC0_SumV[0] += temp0;               /* Add new measured value to the output buffer */
  temp0 = *ResPointer++;               /* Save measured value to temporary variable */
  ADC0_SumV[1] += temp0;               /* Add new measured value to the output buffer */
  temp0 = *ResPointer++;               /* Save measured value to temporary variable */
  ADC0_SumV[2] += temp0;               /* Add new measured value to the output buffer */
  temp0 = *ResPointer++;               /* Save measured value to temporary variable */
  ADC0_SumV[3] += temp0;               /* Add new measured value to the output buffer */
  temp0 = *ResPointer++;               /* Save measured value to temporary variable */
  ADC0_SumV[4] += temp0;               /* Add new measured value to the output buffer */
  temp0 = *ResPointer++;               /* Save measured value to temporary variable */
  ADC0_SumV[5] += temp0;               /* Add new measured value to the output buffer */
  SumCnt++;                            /* Update counter of the conversion cycles */
  if (SumCnt == 2U) {                  /* All requested conversions have been measured */
    OutFlg = TRUE;                     /* Measured values are available */
    ADC0_OutV[0] = ADC0_SumV[0];       /* Save measured value to the output buffer */
    ADC0_OutV[1] = ADC0_SumV[1];       /* Save measured value to the output buffer */
    ADC0_OutV[2] = ADC0_SumV[2];       /* Save measured value to the output buffer */
    ADC0_OutV[3] = ADC0_SumV[3];       /* Save measured value to the output buffer */
    ADC0_OutV[4] = ADC0_SumV[4];       /* Save measured value to the output buffer */
    ADC0_OutV[5] = ADC0_SumV[5];       /* Save measured value to the output buffer */
    if (ModeFlg != MEASURE) {          /* Running in continuous or trigger mode? */
     /* Note: Next 6 lines are speed optimized */
     ADC0_SumV[0] = 0U;                /* Set variable for storing measured values to 0 */
     ADC0_SumV[1] = 0U;                /* Set variable for storing measured values to 0 */
     ADC0_SumV[2] = 0U;                /* Set variable for storing measured values to 0 */
     ADC0_SumV[3] = 0U;                /* Set variable for storing measured values to 0 */
     ADC0_SumV[4] = 0U;                /* Set variable for storing measured values to 0 */
     ADC0_SumV[5] = 0U;                /* Set variable for storing measured values to 0 */
      SumCnt = 0x00U;                  /* Clear the number of conversions */
    } else {
      ModeFlg = IDLE;                  /* Set the component to the IDLE mode */
    }
    ADC0_OnEnd();                      /* If yes then invoke user event */
  }
  if (ModeFlg != IDLE) {
    while((ADC0STS & ADC0STS_READY_MASK) == 0x00U) {} /* Wait until the periphery is in idle state */
    /* ADC0FLWCTL: SEQA=0,TRIG=0,RSTA=1,LDOK=0,??=0,??=0,??=0,??=0 */
    setReg8(ADC0FLWCTL, 0x20U);        /* RSTA for prepare of the next measurement */ 
    while(ADC0FLWCTL != 0x00U) {}      /* Wait until the restart event is not finished */
    /* ADC0FLWCTL: SEQA=0,TRIG=1,RSTA=0,LDOK=0,??=0,??=0,??=0,??=0 */
    setReg8(ADC0FLWCTL, 0x40U);        /* TRIG for start of the measurement */ 
  }
}

#pragma CODE_SEG ADC0_CODE
/*
** ===================================================================
**     Method      :  ADC0_ErrorInterrupt (component ADC)
**
**     Description :
**         The method services the interrupt of the selected peripheral(s)
**         and eventually invokes event(s) of the component.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
#pragma CODE_SEG __NEAR_SEG NON_BANKED
ISR(ADC0_ErrorInterrupt)
{
  if ((ADC0EIF & CEASE_ERROR_MASK) != 0U) {
    ModeFlg = IDLE;
    /* ADC0CTL: ADC_SR=1 */
    setReg16Bits(ADC0CTL, 0x4000U);    /* Trigger the soft reset */ 
  } else {
    /* ADC0EIF: IA_EIF=0,CMD_EIF=0,EOL_EIF=0,??=0,TRIG_EIF=0,RSTAR_EIF=1,LDOK_EIF=1,??=0 */
    setReg8(ADC0EIF, 0x06U);           /* Clear Non cease error flag */ 
    /* ADC0IF: SEQAD_IF=0,CONIF_OIF=1,??=0,??=0,??=0,??=0,??=0,??=0 */
    setReg8(ADC0IF, 0x40U);            /* Clear flags in the Interrupt flag register */ 
  }
  ADC0_OnError();                      /* If yes then invoke user event */
}

#pragma CODE_SEG ADC0_CODE
/*
** ===================================================================
**     Method      :  ADC0_AbortInterrupt (component ADC)
**
**     Description :
**         The method services the interrupt of the selected peripheral(s)
**         and eventually invokes event(s) of the component.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
#pragma CODE_SEG __NEAR_SEG NON_BANKED
ISR(ADC0_AbortInterrupt)
{
  /* ADC0IF: SEQAD_IF=1,CONIF_OIF=0,??=0,??=0,??=0,??=0,??=0,??=0 */
  setReg8(ADC0IF, 0x80U);              /* Clear Abort flag */ 
  ModeFlg = IDLE;
  ADC0_OnAbort();                      /* If yes then invoke user event */
}

#pragma CODE_SEG ADC0_CODE
/*
** ===================================================================
**     Method      :  ADC0_Init (component ADC)
**
**     Description :
**         Initializes the associated peripheral(s) and the components 
**         internal variables. The method is called automatically as a 
**         part of the application initialization code.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
void ADC0_Init(void)
{
  OutFlg = FALSE;                      /* No measured value */
  ModeFlg = IDLE;                      /* Device isn't running */
  /* ADC0CTL: ADC_EN=0,ADC_SR=0,FRZ_MOD=0,SWAI=0,ACC_CFG=0,STR_SEQA=0,MOD_CFG=0,CSL_BMOD=0,RVL_BMOD=0,SMOD_ACC=0,AUT_RSTA=0,??=0,??=0,??=0,??=0 */
  setReg16(ADC0CTL, 0x00U);            /* Disable periphery to make accesible WP bits in enable mode */ 
  ADC0CBP = CSL;
  ADC0RBP = RVL;
  /* ADC0FMT: DJM=0,??=0,??=0,??=0,??=0,SRES=4 */
  setReg8(ADC0FMT, 0x04U);             /* Set Format register */ 
  /* ADC0TIM: ??=0,PRS=0x11 */
  setReg8(ADC0TIM, 0x11U);             /* Set Timing register */ 
  /* ADC0CROFF1: ??=0,CMDRES_OFF1=0 */
  setReg8(ADC0CROFF1, 0x00U);          /* Set Command and Result Offset 1 register */ 
  /* ADC0EIF: IA_EIF=0,CMD_EIF=0,EOL_EIF=0,??=0,TRIG_EIF=0,RSTAR_EIF=1,LDOK_EIF=1,??=0 */
  setReg8(ADC0EIF, 0x06U);             /* Clear error flag that could be cleared by write 1 */ 
  /* ADC0EIE: IA_EIE=1,CMD_EIE=1,EOL_EIE=1,??=1,TRIG_EIE=1,RSTAR_EIE=1,LDOK_EIE=0,??=0 */
  setReg8(ADC0EIE, 0xFCU);             /* Set Error interrupt enable register */ 
  /* ADC0IF: SEQAD_IF=1,CONIF_OIF=1,??=0,??=0,??=0,??=0,??=0,??=0 */
  setReg8(ADC0IF, 0xC0U);              /* Clear other flags */ 
  /* ADC0IE: SEQAD_IE=1,CONIF_OIE=1,??=0,??=0,??=0,??=0,??=0,??=0 */
  setReg8(ADC0IE, 0xC0U);              /* Set Abort and Conversion overrun interrupt */ 
  /* ADC0CONIF: CON_IF15=0,CON_IF14=0,CON_IF13=0,CON_IF12=0,CON_IF11=0,CON_IF10=0,CON_IF9=0,CON_IF8=0,CON_IF7=0,CON_IF6=0,CON_IF5=0,CON_IF4=0,CON_IF3=0,CON_IF2=0,CON_IF1=0,EOL_IF=1 */
  setReg16(ADC0CONIF, 0x01U);          /* Clear scan cycle complete flag */ 
  /* ADC0CONIE: CON_IE15=0,CON_IE14=0,CON_IE13=0,CON_IE12=0,CON_IE11=0,CON_IE10=0,CON_IE9=0,CON_IE8=0,CON_IE7=0,CON_IE6=0,CON_IE5=0,CON_IE4=0,CON_IE3=0,CON_IE2=0,CON_IE1=0,EOL_IE=1 */
  setReg16(ADC0CONIE, 0x01U);          /* Set End of list interrupt in Conversion interrupt enable register */ 
  /* ADC0CTL: ADC_EN=1,ADC_SR=0,FRZ_MOD=0,SWAI=0,ACC_CFG=2,STR_SEQA=0,MOD_CFG=0,CSL_BMOD=0,RVL_BMOD=1,SMOD_ACC=0,AUT_RSTA=0,??=0,??=0,??=0,??=0 */
  setReg16(ADC0CTL, 0x8840U);          /* Set Control register */ 
}

/* END ADC0. */

/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.3 [05.09]
**     for the Freescale HCS12Z series of microcontrollers.
**
** ###################################################################
*/
